"""empty message

Revision ID: 000c9380b984
Revises: af258dbff96f
Create Date: 2026-07-21 11:04:47.823147

"""
from typing import Sequence, Union

from alembic import op
from pgvector.sqlalchemy import Vector
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '000c9380b984'
down_revision: Union[str, Sequence[str], None] = 'af258dbff96f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE EXTENSION IF NOT EXISTS vector')
    op.create_table('presupuestos_embeddings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('presupuesto_id', sa.Integer(), nullable=False),
    sa.Column('contenido_indexado', sa.Text(), nullable=False),
    sa.Column('embedding', Vector(384), nullable=False),
    sa.Column('modelo_embedding', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['presupuesto_id'], ['presupuestos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('presupuesto_id')
    )
    op.create_index(op.f('ix_presupuestos_embeddings_embedding'), 'presupuestos_embeddings', ['embedding'], unique=False)
    op.create_table('detalles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('capitulo_id', sa.Integer(), nullable=True),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('unidad', sa.String(length=20), nullable=False),
    sa.Column('cantidad', sa.Numeric(), nullable=False),
    sa.Column('precio_unitario', sa.Numeric(), nullable=False),
    sa.Column('subtotal', sa.Numeric(), nullable=False),
    sa.Column('generado_por_ia', sa.Boolean(), nullable=False),
    sa.Column('precio_confirmado', sa.Boolean(), nullable=False),
    sa.Column('es_externo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['capitulo_id'], ['capitulos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('presupuestos_embeddings')
    op.drop_table('detalles')
    op.drop_index(op.f('ix_presupuestos_embeddings_embedding'), table_name='presupuestos_embeddings', if_exists=True)
    op.drop_table('presupuestos_embeddings')
    # ### end Alembic commands ###
