"""empty message

Revision ID: 000c9380b984
Revises: af258dbff96f
Create Date: 2026-07-21 11:04:47.823147

"""
from typing import Sequence, Union

from alembic import op
from pgvector.sqlalchemy import Vector
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '000c9380b984'
down_revision: Union[str, Sequence[str], None] = 'af258dbff96f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE EXTENSION IF NOT EXISTS vector')
    op.execute(
        "ALTER TYPE estadopresupuesto RENAME VALUE 'En Revision' TO 'En Revisión'")
    op.create_table('presupuestos_embeddings',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('presupuesto_id', sa.Integer(), nullable=False),
                    sa.Column('contenido_indexado', sa.Text(), nullable=False),
                    sa.Column('embedding', Vector(384), nullable=False),
                    sa.Column('modelo_embedding', sa.String(
                        length=255), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_at', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.ForeignKeyConstraint(['presupuesto_id'], [
                        'presupuestos.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('presupuesto_id')
                    )
    op.execute("ALTER TYPE estadopresupuesto RENAME TO estadopresupuesto_old")
    op.execute(
        "CREATE TYPE estadopresupuesto AS ENUM ('Borrador', 'Enviado', 'En Revisión', 'Aprobado', 'Rechazado')")
    op.execute(
        "ALTER TABLE presupuestos ALTER COLUMN estado TYPE estadopresupuesto USING estado::text::estadopresupuesto")
    op.execute("DROP TYPE estadopresupuesto_old")
    op.create_index(op.f('ix_presupuestos_embeddings_embedding'),
                    'presupuestos_embeddings', ['embedding'], unique=False)
    op.create_table('detalles',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('capitulo_id', sa.Integer(), nullable=True),
                    sa.Column('numero', sa.Integer(), nullable=False),
                    sa.Column('descripcion', sa.Text(), nullable=False),
                    sa.Column('unidad', sa.String(length=20), nullable=False),
                    sa.Column('cantidad', sa.Numeric(), nullable=False),
                    sa.Column('precio_unitario', sa.Numeric(), nullable=False),
                    sa.Column('subtotal', sa.Numeric(), nullable=False),
                    sa.Column('generado_por_ia', sa.Boolean(), nullable=False),
                    sa.Column('precio_confirmado',
                              sa.Boolean(), nullable=False),
                    sa.Column('es_externo', sa.Boolean(), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_at', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['capitulo_id'], ['capitulos.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.execute("ALTER TABLE presupuestos ALTER COLUMN estado TYPE text")
    op.execute("DROP TYPE estadopresupuesto")

    # 2. Actualizar los valores existentes a title case
    op.execute(
        "UPDATE presupuestos SET estado = 'Borrador' WHERE estado = 'BORRADOR'")
    op.execute(
        "UPDATE presupuestos SET estado = 'Enviado' WHERE estado = 'ENVIADO'")
    op.execute(
        "UPDATE presupuestos SET estado = 'Aprobado' WHERE estado = 'ACEPTADO'")
    op.execute(
        "UPDATE presupuestos SET estado = 'Rechazado' WHERE estado = 'RECHAZADO'")

    # 3. Crear el nuevo enum y reconvertir
    op.execute(
        "CREATE TYPE estadopresupuesto AS ENUM ('Borrador', 'Enviado', 'En Revisión', 'Aprobado', 'Rechazado')")
    op.execute(
        "ALTER TABLE presupuestos ALTER COLUMN estado TYPE estadopresupuesto USING estado::estadopresupuesto")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('presupuestos_embeddings')
    op.drop_table('detalles')
    op.drop_index(op.f('ix_presupuestos_embeddings_embedding'),
                  table_name='presupuestos_embeddings', if_exists=True)
    op.drop_table('presupuestos_embeddings')
    # ### end Alembic commands ###
    op.execute("ALTER TYPE estadopresupuesto RENAME TO estadopresupuesto_old")
    op.execute(
        "CREATE TYPE estadopresupuesto AS ENUM ('BORRADOR', 'ENVIADO', 'ACEPTADO', 'RECHAZADO')")
    op.execute(
        "ALTER TABLE presupuestos ALTER COLUMN estado TYPE estadopresupuesto USING estado::text::estadopresupuesto")
    op.execute("DROP TYPE estadopresupuesto_old")
