"""change estado to string

Revision ID: 0fbea77c1da4
Revises: 8c8be7742803
Create Date: 2026-08-03 21:22:23.621061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0fbea77c1da4'
down_revision: Union[str, Sequence[str], None] = '8c8be7742803'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('presupuestos', 'estado',
               existing_type=postgresql.ENUM('Borrador', 'Enviado', 'En Revisión', 'Aprobado', 'Rechazado', name='estadopresupuesto'),
               type_=sa.String(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('presupuestos', 'estado',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('Borrador', 'Enviado', 'En Revisión', 'Aprobado', 'Rechazado', name='estadopresupuesto'),
               existing_nullable=False)
    # ### end Alembic commands ###
