"""empty message

Revision ID: 49e0bb87abe3
Revises: f24e7d68c77f
Create Date: 2026-08-09 02:21:04.442393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49e0bb87abe3'
down_revision: Union[str, Sequence[str], None] = 'f24e7d68c77f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('razon_social', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('direccion_fiscal', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('documento', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('telefono', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('web', sa.String(length=255), nullable=True))
    op.drop_constraint(op.f('users_username_key'), 'users', type_='unique')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('users_username_key'), 'users', ['username'], postgresql_nulls_not_distinct=False)
    op.drop_column('users', 'web')
    op.drop_column('users', 'telefono')
    op.drop_column('users', 'documento')
    op.drop_column('users', 'direccion_fiscal')
    op.drop_column('users', 'razon_social')
    # ### end Alembic commands ###
