"""empty message

Revision ID: 91241450be2e
Revises: 4498ade5e670
Create Date: 2026-08-03 16:12:39.032627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91241450be2e'
down_revision: Union[str, Sequence[str], None] = '4498ade5e670'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clientes', sa.Column('estado', sa.String(length=50), nullable=True))
    op.add_column('clientes', sa.Column('tipo', sa.String(length=50), nullable=True))
    op.add_column('clientes', sa.Column('cif', sa.String(length=20), nullable=True))
    op.add_column('clientes', sa.Column('notas', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clientes', 'notas')
    op.drop_column('clientes', 'cif')
    op.drop_column('clientes', 'tipo')
    op.drop_column('clientes', 'estado')
    # ### end Alembic commands ###
