"""empty message

Revision ID: 9f3ef9d40665
Revises: fd8986eea9ae
Create Date: 2026-08-16 15:44:47.863814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f3ef9d40665'
down_revision: Union[str, Sequence[str], None] = 'fd8986eea9ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clientes', sa.Column('codigo', sa.String(length=50), nullable=True))
    op.create_unique_constraint(None, 'clientes', ['codigo'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'clientes', type_='unique')
    op.drop_column('clientes', 'codigo')
    # ### end Alembic commands ###
