"""empty message

Revision ID: cdae59b78eee
Revises: 7645e921fd2e
Create Date: 2026-07-27 19:27:37.117897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdae59b78eee'
down_revision: Union[str, Sequence[str], None] = '7645e921fd2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_cliente', sa.Text(), nullable=False),
    sa.Column('direccion', sa.Text(), nullable=True),
    sa.Column('poblacion', sa.String(length=400), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('presupuestos', sa.Column('cliente_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'presupuestos', 'clientes', ['cliente_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'presupuestos', type_='foreignkey')
    op.drop_column('presupuestos', 'cliente_id')
    op.drop_table('clientes')
    # ### end Alembic commands ###
