"""empty message

Revision ID: fd8986eea9ae
Revises: 6d6fe4af02a4
Create Date: 2026-08-14 12:46:19.856924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd8986eea9ae'
down_revision: Union[str, Sequence[str], None] = '6d6fe4af02a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('razon_social', sa.String(length=255), nullable=True),
    sa.Column('direccion_fiscal', sa.String(length=255), nullable=True),
    sa.Column('documento', sa.String(length=20), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('web', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.add_column('clientes', sa.Column('empresa_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'clientes', 'empresa', ['empresa_id'], ['id'])
    op.add_column('presupuestos', sa.Column('empresa_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'presupuestos', 'empresa', ['empresa_id'], ['id'])
    op.add_column('users', sa.Column('empresa_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('nombre_completo', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('cargo', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('rol', sa.String(length=20), nullable=True))
    op.create_foreign_key(None, 'users', 'empresa', ['empresa_id'], ['id'])
    op.drop_column('users', 'direccion_fiscal')
    op.drop_column('users', 'documento')
    op.drop_column('users', 'razon_social')
    op.drop_column('users', 'web')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('web', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('razon_social', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('documento', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('direccion_fiscal', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'rol')
    op.drop_column('users', 'cargo')
    op.drop_column('users', 'nombre_completo')
    op.drop_column('users', 'empresa_id')
    op.drop_constraint(None, 'presupuestos', type_='foreignkey')
    op.drop_column('presupuestos', 'empresa_id')
    op.drop_constraint(None, 'clientes', type_='foreignkey')
    op.drop_column('clientes', 'empresa_id')
    op.drop_table('empresa')
    # ### end Alembic commands ###
