services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/dockerfile
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    env_file:
      - ../.env

 


